main: main.Main
name: HealthManager2
version: 2.0
website: jandie1505.net
commands:
  healthmanager:
    description: Shows informations
    usage: /healthmanager
  heal:
    description: Heal yourself (or any other player)
    usage: /heal (<Spieler>)