main: main.Main
name: HealthManager2
version: 2.0
website: jandie1505.net
api-version: 1.16
softdepend: [PlaceholderAPI]
commands:
  healthmanager:
    description: Shows informations
    usage: /healthmanager
  heal:
    description: Heal yourself (or any other player)
    usage: /heal (<Player>)
    permission: healthmanager.heal
  sethealth:
    description: Set the lives of a specific player
    usage: /sethealth <Player> <Amount>
    permission: healthmanager.sethealth
  sethunger:
    description: Set the food level of a specific player
    usage: /sethunger <Player> <Amount>
    permission: healthmanager.sethunger
  gethealth:
    description: Shows the amount of lives of a specific player
    usage: /gethealth <Player>
    permission: healthmanager.gethealth
  gethunger:
    description: Shows the food level of a specific player
    usage: /gethunger <Player>
    permission: healthmanager.gethunger
  setmaxhealth:
    description: Set the max health for a specific player
    usage: /setmaxhealth <Player> <Amount>
    permission: healthmanager.setmaxhealth
  getmaxhealth:
    description: Shows the max health of a specific player
    usage: /getmaxhealth <Player>
    permission: healthmanager.getmaxhealth
  setsaturation:
    description: Set the saturation level for a specific player
    usage: /setsaturation <Player> <Amount>
    permission: healthmanager.setsaturation
  getsaturation:
    description: Shows the saturation level of a specific player
    usage: /getsaturation <Player>
    permission: healthmanager.getsaturation
  feed:
    description: Feed yourself (or any other player)
    usage: /feed (<Player>)
    permission: healthmanager.feed
  saturationmode:
    description: Turn Saturationmode on/off for yourself (and other players)
    usage: /saturationmode (<Player>)
    permission: healthmanager.saturationmode
  god:
    description: Turn Godmode on/off for yourself (and other players)
    usage: /god (<Player>)
    permission: healthmanager.godmode