main: main.Main
name: HealthManager2
version: 2.0
website: jandie1505.net
commands:
  healthmanager:
    description: Shows informations
    usage: /healthmanager
  heal:
    description: Heal yourself (or any other player)
    usage: /heal (<Player>)
  sethealth:
    description: Set the lives of a specific player
    usage: /sethealth <Player> <Amount>
  sethunger:
    description: Set the food level of a specific player
    usage: /sethunger <Player> <Amount>
  gethealth:
    description: Shows the amount of lives of a specific player
    usage: /gethealth <Player>
  gethunger:
    description: Shows the food level of a specific player
    usage: /gethunger <Player>